name: scan the jar file

on: [push]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: test echo command
        run: echo "this is the test"
      - name: create artifact directory
        run: mkdir -p /artifact
      - name: create file
      - run: echo hello > /artifact/world.txt
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/world.txt