name: scan the jar file

on: [push]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2
      - name: Uploading the artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            **/*-${{ github.run_id}}.jar
      # - name: veracode scan
      #   uses: veracode/veracode-uploadandscan-action@0.2.1
      #   with:
      #     appname: 'artifact'
      #     createprofile: false
      #     filepath: '**/**.jar'
      #     vid: '${{ secrets.API_ID }}'
      #     vkey: '${{ secrets.API_KEY }}'
#          createsandbox: 'true'
#          sandboxname: 'SANDBOXNAME'
#          scantimeout: 0
#          exclude: '*.js'
#          include: '*.war'
#          criticality: 'VeryHigh'
  publish-on-atrifactory:
    runs-on: ubuntu-latest
    needs: run-shell-command
    steps:
      - name: publish on artifactory
        uses: actions/checkout@v2
      - name: Downloading the artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
      - run: |
          pwd
          curl -uhelpcoin@outlook.com:Hotmail@123 -T ./${m}-${{ github.run_id}}.jar "https://helpcoin.jfrog.io/artifactory/example-repo-local/${m}-${{ github.run_id}}.jar"
          done