name: scan the jar file

on: [push]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: test echo command
        run: echo "this is the test"
      - name: Checkout repository
        uses: actions/checkout@v3