name: scan the jar file

on: [push]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2
      - name: Uploading the artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ${{ GITHUB_WORKSPACE }}
      - name: veracode scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          appname: 'VeraDemo'
          createprofile: false
          filepath: '**/**.jar'
          vid: '${{ secrets.API_ID }}'
          vkey: '${{ secrets.API_KEY }}'
#          createsandbox: 'true'
#          sandboxname: 'SANDBOXNAME'
#          scantimeout: 0
#          exclude: '*.js'
#          include: '*.war'
#          criticality: 'VeryHigh'